### ISSUE TITLE
[contracts] USDT-like asset transfer

### ISSUE THREAD

**Issue by LayneHaber** [connext/vector#118]
**Describe the bug**
The transfer of USDT-like assets currently results in a double-spend, and we should be more restrictive about what we consider a failed transfer.

We should always bias towards locked funds over double spends.

**Comment by HeikoFisch** [comment]
Is that a new bug you discovered since, or is this supposed to be a summary of Friday's discussion?
It is my understanding that standard-conforming as well as missing-return-value-bug tokens like USDT are safe to use. Only for tokens that ignore the standard even more blatantly -- which means they return something that is not a boolean -- could such a double-spend occur. And we don't support such tokens to begin with. However, in order to introduce an additional safety net, just in case such a token makes it into the system anyway, the suggestion was made to interpret a non-boolean return value as success -- rather than failure, as is currently the case --, thus favoring frozen funds over double-spends, in case our interpretation was wrong (taking also into account that the "frozen" funds can still be withdrawn cooperatively).

**Comment by LayneHaber** [comment]
This is supposed to be the a summary of the Friday discussion, not a new issue. Your summary is definitely better. Is this a duplicate of #121 ?

**Comment by HeikoFisch** [comment]
Ok, no worries! I just wanted to make sure I don't accidentally discard what would be a very serious issue in case I misunderstood.

It's not a duplicate. While this issue is about transfers out of the channel, #121 deals with transfers into the channel (for Alice). The latter still only work with a strictly standard-compliant token.
