### ISSUE TITLE
[router] Validate params prior to creating receiver transfer

### ISSUE THREAD

**Issue by ArjunBhuptani** [connext/vector#288]
It's unsafe for a router to cancel a sender-side transfer if it has already `created` a transfer to the receiver.

This means that there are cases where a router might initiate a receiver side transfer without having sufficient funds, with the idea that the transfer would fail in the lower level protocol. We should instead do some simple checks in the router too so that we can fail fast and cancel sender-side transfer *before* the flow gets to the protocol layer

**Comment by LayneHaber** [comment]
When would this hit the low-level protocol?

If depositing without sufficient funds, the `send-deposit-tx` call to the node [should fail](https://github.com/connext/vector/blob/d324a1b0015409a14c8b80575d93415ae26828a6/modules/router/src/collateral.ts#L99-L114), causing a [sender-side cancel](https://github.com/connext/vector/blob/d324a1b0015409a14c8b80575d93415ae26828a6/modules/router/src/services/transfer.ts#L92-L101) (because the recipient transfer was never attempted). Additionally, because of how the `deposit` protocol works it still shouldn't hit the lower-level `deposit` function if the onchain tx to the multisig fails.
