### ISSUE TITLE
[contracts] Move back to `execWithdraw` pattern where arbitrary withdraw txs can be executed

### ISSUE THREAD

**Issue by ArjunBhuptani** [connext/vector#32]
We *should not* restrict this at the contract level

**Comment by bohendo** [comment]
IMO our time would be *much* better spent finishing disputes rather than adding this feature.

I thought the whole point of vector was to strip out any unnecessary complexity. Is there a single use case we plan to support in the near future that needs arbitrary tx withdrawals?

It's not like the first set of contracts we deploy will be the last. If we need more flexibility later, there's be plenty of time to add it.

**Comment by LayneHaber** [comment]
I think this is definitely lower on the priority list than any of the other outstanding issues in the description of #114 cc @ArjunBhuptani

**Comment by bohendo** [comment]
Let's shelve this for the next week or so or until we have a compelling reason to add this feature
