### ISSUE TITLE
RFC re Transfers

### ISSUE THREAD

**Issue by bohendo** [connext/vector#5]
Currently:
 - LinkedTransfer resolves based on a hash preImage & optionally accepts a recipient who's allowed to resolve 
 - HashlockTransfer resolves based on a hash preImage & enforces a timeout
 - SignedTransfer resolves based on a signature w/out a timeout

I propose:
 - HashlockTransfer resolves based on a hash preImage
 - SignedTransfer resolves based on a signature
 - both accept an expiry after which the transfer gets reverted, 0 means it never expires

Core transfer params would be: `(type: "SignedTransfer" | "HashlockTransfer", payload: NonceToSign | HashedPreImage, timeout: number)`

SignedTransfer would become `createTransfer("SignedTransfer", nonce, 0)`
HashlockTransfer would become `createTransfer("HashlockTransfer", hash, timeout)`
LinkedTransfer w recipient specified would become `createTransfer("SignedTransfer", nonce, 0)`
LinkedTransfer w/out a recipient would become `createTransfer("HashlockTransfer", hash, 0)`

We could consider pulling the expiry enforcement logic into the adjudicator too to prevent it from being duplicated across every app definition.

**Comment by ArjunBhuptani** [comment]
I really like the idea of building in timeouts into the transfers themselves. That makes sense as a convention, at least for the hashlocks.

I think adding more generality to signing will be a bit tough. That's how we had it originally but folks want to have access to the data that was signed, and also want it to be properly domain-separated. There's limitations to how generalized we can make that while retaining (a) the ability to use pureEVM, and (b) passing in data as encodedParams. Perhaps we can come back to this one with some more user data.

The nice thing about Vector is that modifying the behavior for these transfers will be *much much* easier than what exists with indra currently. All of the logic around adding/removing transfer types happens in the engine within the param converters (rather than being spread out through the entire stack).
